### ISSUE TITLE
PotionRunnable missing this.level = level;

### ISSUE THREAD

**Issue by gh0ztbuster** [Eniripsa96/EnchantmentPack#4]
I'll cut right to the chase; you are missing "this.level = level;" after line 37 in PotionRunnable under the passive section of EnchantPotionPacks. The level or tier isn't applied to the enchantment without this line of code.

You're plugin is great and I love your code :)

**Comment by Eniripsa96** [comment]
Thanks for pointing it out, I will update it with this fix.
